#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplomna_rabota.Data_tables
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Drugs")]
	public partial class DrugsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DrugsDataContext() : 
				base(global::diplomna_rabota.Properties.Settings.Default.DrugsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DrugsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DrugsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DrugsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DrugsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Drug> Drugs
		{
			get
			{
				return this.GetTable<Drug>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Drugs")]
	public partial class Drug
	{
		
		private string _Генерично_име;
		
		private string _Търговско_име;
		
		private string _Производител;
		
		private string _Лекарствена_форма;
		
		private string _НЗОК_код;
		
		private string _Групи_терапевтични_агенти;
		
		private string _Механизъм_на_действие;
		
		private string _Нежелани_лекарствени_действия;
		
		private string _Специални_противопоказания;
		
		private string _Кратка_лекарствена_характеристика;
		
		public Drug()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Генерично име]", Storage="_Генерично_име", DbType="NChar(40)")]
		public string Генерично_име
		{
			get
			{
				return this._Генерично_име;
			}
			set
			{
				if ((this._Генерично_име != value))
				{
					this._Генерично_име = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Търговско име]", Storage="_Търговско_име", DbType="NChar(40)")]
		public string Търговско_име
		{
			get
			{
				return this._Търговско_име;
			}
			set
			{
				if ((this._Търговско_име != value))
				{
					this._Търговско_име = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Производител", DbType="NChar(30)")]
		public string Производител
		{
			get
			{
				return this._Производител;
			}
			set
			{
				if ((this._Производител != value))
				{
					this._Производител = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Лекарствена форма]", Storage="_Лекарствена_форма", DbType="NChar(10)")]
		public string Лекарствена_форма
		{
			get
			{
				return this._Лекарствена_форма;
			}
			set
			{
				if ((this._Лекарствена_форма != value))
				{
					this._Лекарствена_форма = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[НЗОК код]", Storage="_НЗОК_код", DbType="NChar(10)")]
		public string НЗОК_код
		{
			get
			{
				return this._НЗОК_код;
			}
			set
			{
				if ((this._НЗОК_код != value))
				{
					this._НЗОК_код = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Групи терапевтични агенти]", Storage="_Групи_терапевтични_агенти", DbType="NChar(100)")]
		public string Групи_терапевтични_агенти
		{
			get
			{
				return this._Групи_терапевтични_агенти;
			}
			set
			{
				if ((this._Групи_терапевтични_агенти != value))
				{
					this._Групи_терапевтични_агенти = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Механизъм на действие]", Storage="_Механизъм_на_действие", DbType="NChar(200)")]
		public string Механизъм_на_действие
		{
			get
			{
				return this._Механизъм_на_действие;
			}
			set
			{
				if ((this._Механизъм_на_действие != value))
				{
					this._Механизъм_на_действие = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Нежелани лекарствени действия]", Storage="_Нежелани_лекарствени_действия", DbType="NChar(200)")]
		public string Нежелани_лекарствени_действия
		{
			get
			{
				return this._Нежелани_лекарствени_действия;
			}
			set
			{
				if ((this._Нежелани_лекарствени_действия != value))
				{
					this._Нежелани_лекарствени_действия = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Специални противопоказания]", Storage="_Специални_противопоказания", DbType="NChar(200)")]
		public string Специални_противопоказания
		{
			get
			{
				return this._Специални_противопоказания;
			}
			set
			{
				if ((this._Специални_противопоказания != value))
				{
					this._Специални_противопоказания = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Кратка лекарствена характеристика]", Storage="_Кратка_лекарствена_характеристика", DbType="NChar(70)")]
		public string Кратка_лекарствена_характеристика
		{
			get
			{
				return this._Кратка_лекарствена_характеристика;
			}
			set
			{
				if ((this._Кратка_лекарствена_характеристика != value))
				{
					this._Кратка_лекарствена_характеристика = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
