#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplomna_rabota.Data_tables
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MKb")]
	public partial class MKBDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MKBDataClassesDataContext() : 
				base(global::diplomna_rabota.Properties.Settings.Default.MKbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MKBDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MKBDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MKBDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MKBDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MKB> MKBs
		{
			get
			{
				return this.GetTable<MKB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MKB")]
	public partial class MKB
	{
		
		private string _МКБ_код;
		
		private string _Болест;
		
		public MKB()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[МКБ код]", Storage="_МКБ_код", DbType="NChar(10)")]
		public string МКБ_код
		{
			get
			{
				return this._МКБ_код;
			}
			set
			{
				if ((this._МКБ_код != value))
				{
					this._МКБ_код = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Болест", DbType="NChar(60)")]
		public string Болест
		{
			get
			{
				return this._Болест;
			}
			set
			{
				if ((this._Болест != value))
				{
					this._Болест = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
