#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplomna_rabota
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Drugs")]
	public partial class MedicineDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MedicineDataContext() : 
				base(global::diplomna_rabota.Properties.Settings.Default.DrugsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MedicineDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MedicineDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MedicineDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MedicineDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Drug> Drugs
		{
			get
			{
				return this.GetTable<Drug>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Drugs")]
	public partial class Drug
	{
		
		private string _GenericName;
		
		private string _MedicineName;
		
		private string _Producer;
		
		private string _MedForm;
		
		private string _NZOKCode;
		
		private string _TerapyAgent;
		
		private string _Action;
		
		private string _SideEffect;
		
		private string _ContraIndication;
		
		private string _MedicineDescrip;
		
		public Drug()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Генерично име]", Storage="_GenericName", DbType="VarChar(150)")]
		public string GenericName
		{
			get
			{
				return this._GenericName;
			}
			set
			{
				if ((this._GenericName != value))
				{
					this._GenericName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Търговско име]", Storage="_MedicineName", DbType="VarChar(200)")]
		public string MedicineName
		{
			get
			{
				return this._MedicineName;
			}
			set
			{
				if ((this._MedicineName != value))
				{
					this._MedicineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Производител", Storage="_Producer", DbType="VarChar(200)")]
		public string Producer
		{
			get
			{
				return this._Producer;
			}
			set
			{
				if ((this._Producer != value))
				{
					this._Producer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Лекарствена форма]", Storage="_MedForm", DbType="VarChar(200)")]
		public string MedForm
		{
			get
			{
				return this._MedForm;
			}
			set
			{
				if ((this._MedForm != value))
				{
					this._MedForm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[НЗОК код]", Storage="_NZOKCode", DbType="VarChar(50)")]
		public string NZOKCode
		{
			get
			{
				return this._NZOKCode;
			}
			set
			{
				if ((this._NZOKCode != value))
				{
					this._NZOKCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Групи терапевтични агенти]", Storage="_TerapyAgent", DbType="VarChar(200)")]
		public string TerapyAgent
		{
			get
			{
				return this._TerapyAgent;
			}
			set
			{
				if ((this._TerapyAgent != value))
				{
					this._TerapyAgent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Механизъм на действие]", Storage="_Action", DbType="VarChar(200)")]
		public string Action
		{
			get
			{
				return this._Action;
			}
			set
			{
				if ((this._Action != value))
				{
					this._Action = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Нежелани лекарствени действия]", Storage="_SideEffect", DbType="VarChar(200)")]
		public string SideEffect
		{
			get
			{
				return this._SideEffect;
			}
			set
			{
				if ((this._SideEffect != value))
				{
					this._SideEffect = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Специални противопоказания]", Storage="_ContraIndication", DbType="VarChar(200)")]
		public string ContraIndication
		{
			get
			{
				return this._ContraIndication;
			}
			set
			{
				if ((this._ContraIndication != value))
				{
					this._ContraIndication = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Кратка лекарствена характеристика]", Storage="_MedicineDescrip", DbType="VarChar(100)")]
		public string MedicineDescrip
		{
			get
			{
				return this._MedicineDescrip;
			}
			set
			{
				if ((this._MedicineDescrip != value))
				{
					this._MedicineDescrip = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
